### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by NiccoloGranieri** [theOneAndOnlyOne/BeReel#12]
First of all, thank you for this amazing tool. It works like a charm, and I was able to create my 2023 recap (however, I am a Python dev, so it was a bit easier for me).

Missing requirements:
- The script (on macOS) requires ffmpeg to be installed locally. I personally installed it via brew, but for non-developers that would also require to install Brew which might be an additional barrier.

`brew install ffmpeg`

- The script also requires cv2, that can be easily added to the requirements.txt file and installed via pip.

`pip install opencv-python`

Finally, for some reason, if the auth-code is inserted automagically via macOS' latest "Autofill from email" feature, the script crashes. The authentication code _needs_ to be input by hand.

I am happy to contribute to the project via PRs and or by writing documentation if you'd like me to, just let me know what's the preferred way of contribution and I'll see what I can do.

Happy New Year!

**Comment by BassCoder2808** [comment]
Hi @theOneAndOnlyOne , I would like the update the **README.md** and the **requirements.txt** based on the suggestions provided by @NiccoloGranieri. If it's okay I will raise the PR for the same

**Comment by theOneAndOnlyOne** [comment]
Hey guys thanks for the comments. If you want to contribute to the project you can raise a pull request and I will merge them to main once I check it out. Wish you guys a Happy New Year as well!
