### ISSUE TITLE
Trying to generate classic recap, getting error

### ISSUE THREAD

**Issue by limelody** [theOneAndOnlyOne/BeReel#13]
Python 3.8
ValueError: Could not find a format to read the specified file in single-image mode
<img width="851" alt="image" src="https://github.com/theOneAndOnlyOne/BeReel/assets/33642485/3cda8f2c-7980-4729-979a-1a9d34975836">

**Comment by limelody** [comment]
I switched to python 3.11 and it no longer has this error. Seems like python 3.8 is not a compatible version

**Comment by theOneAndOnlyOne** [comment]
Thanks for bringing this up @limelody, I'll update the documentation to keep this noted. I'll close this issue now
