### ISSUE TITLE
Program failing if an image is broken

### ISSUE THREAD

**Issue by 1tgis** [theOneAndOnlyOne/BeReel#6]
Personal Idea: Make the program skip the day in the final video so it doesn't shit itself

**Comment by theOneAndOnlyOne** [comment]
Could you send what comes up in the terminal if such an error comes up?

**Comment by 1tgis** [comment]
![grafik](https://github.com/theOneAndOnlyOne/BeReel/assets/102979150/bddc4f11-0056-4fd5-8940-b961f1dc0789)

**Comment by theOneAndOnlyOne** [comment]
A recent merge should address this issue, lemme know if it still comes up

**Comment by theOneAndOnlyOne** [comment]
Hi @1tgis , I just got back from the holidays. Are you still having this issue? If not I can close this thread now
